Sensor Node:
     archive: ''
     attack: ''
     autorun: false
     autorun_delay_seconds: 3
     autorun_interval_seconds: 3
     console_logging_level: 'INFO'     
     enabled_disabled: enabled
     file_logging_level: 'DEBUG'
     gps:
          gps_autostart: false
          gps_tak_beacon: false            # Beacons to HIPRFISR, forwards to TAK
          gps_position:                    # Default starting position
               latitude: 40.712776
               longitude: -74.005974
               altitude: 10.5
          gps_source: saved           # Options: gpsd, Meshtastic, saved, internet
          gps_update_interval_seconds: 20  # 300
          gpsd_serial_port: '/dev/ttyACM0'
     hardware:
          defaults:
               sdr: 0
               wifi_adapter: 1
          sdrs:
               0:
                    radio_name: 'USRP B205mini'
                    type: 'USRP B20xmini'
                    serial: ''
                    daughterboard: ''
                    ip_address: ''
                    network_interface: ''
          wifi_adapters:
               0:
                    radio_name: 'Integrated Wi-Fi'
                    interface: 'wlan0'
                    notes: ''
               1:
                    radio_name: 'USB Wi-Fi Adapter'
                    interface: 'wlx00c0caafc930'
                    notes: ''
     heartbeat_interval: 5
     heartbeat_interval_connected: 60
     hb_port: "6100"
     ip_address: '192.168.1.128'               # '127.0.0.1' for local - HIPRFISR IP Address
     iq:
          0:
               daughterboard: ''
               ip_address: ''
               network_interface: ''
               radio_name: ''
               serial: ''
               type: ''
               uid: ''
     local_remote: remote                   # Does not need to be set, updated during init, "remote" or "local"
     location: Location text
     msg_port: "6101"
     network_type: IP                      # "IP" or "Meshtastic"
     nickname: Remote1
     notes: Notes text
     pd: ''
     meshtastic_serial_port: '/dev/ttyACM1'  # Typically /dev/ttyACM0, /dev/tty/USB0 (make sure gpsd service does not grab port)
     meshtastic_serial_baud_rate: '115200'
     tsi: ''


