Sensor Node:
     archive: ''
     attack: ''
     autorun: false
     autorun_delay_seconds: 3
     autorun_interval_seconds: 3
     console_logging_level: 'INFO'     
     enabled_disabled: enabled
     file_logging_level: 'DEBUG'
     gps:
          gps_autostart: false
          gps_tak_beacon: false            # Beacons to HIPRFISR, forwards to TAK
          gps_position:                    # Default starting position
               latitude: 40.712776
               longitude: -74.005974
               altitude: 10.5
          gps_source: Meshtastic           # gpsd or Meshtastic
          gps_update_interval_seconds: 20  # 300
          gpsd_serial_port: '/dev/ttyACM0'
     hb_port: '5051'     
     ip_address: '127.0.0.1'               # '127.0.0.1' for local, anything else for remote
     iq:
          0:
               daughterboard: ''
               ip_address: ''
               network_interface: ''
               radio_name: ''
               serial: ''
               type: ''
               uid: ''
     local_remote: local                   # Does not need to be set, updated during init, "remote" or "local"
     location: Location text
     msg_port: '5052'
     network_type: IP                      # "IP" or "Meshtastic"
     nickname: Local Sensor Node           # "Local Sensor Node" for local, anything else for remote
     notes: Notes text
     pd: ''
     meshtastic_serial_port: '/dev/ttyACM0'  # Typically /dev/ttyACM0, /dev/tty/USB0 (make sure gpsd service does not grab port)
     meshtastic_serial_baud_rate: '115200'
     tsi: ''


